name: TerraformEC2Provisioner - PROD Destroy

on:
  workflow_dispatch:
    inputs:
      os_type:
        description: "SO das instâncias a destruir (AMAZON_LINUX_2023, UBUNTU_22_04,
          UBUNTU_24_04, WINDOWS_2019, WINDOWS_2022)"
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_myip: ${{ secrets.MY_IP_CIDR }}
  TF_VAR_os_type: ${{ inputs.os_type }}

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform Init
        working-directory: environments/prod
        run: terraform init -upgrade

      - name: Terraform Destroy
        working-directory: environments/prod
        run: terraform destroy -auto-approve
