name: TerraformEC2Provisioner - QA

on:
  push:
    branches:
      - staging
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_myip: ${{ secrets.MY_IP_CIDR }}

jobs:
  Terraform_CI_CD:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform Format Check
        working-directory: environments/qa
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: environments/qa
        run: terraform init -upgrade

      - name: Terraform Validate
        working-directory: environments/qa
        run: terraform validate

      - name: Terraform Plan
        working-directory: environments/qa
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: environments/qa
        run: terraform apply -auto-approve tfplan
