name: TerraformEC2Provisioner

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Terraform Init
        working-directory: environments/prod
        run: terraform init

      - name: Terraform Plan
        working-directory: environments/prod
        run: terraform plan

      - name: Terraform Apply
        working-directory: environments/prod
        run: terraform apply -auto-approve

      - name: Terraform Validate
        working-directory: environments/prod      
        run: terraform validate

      - name: Terraform Destroy
        working-directory: environments/prod      
        run: terraform destroy -auto-approve        
